# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveManger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('current_level', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Active Manager',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('current_level', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=True)),
                ('manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Manager')),
            ],
            options={
                'verbose_name_plural': 'Staff Manager',
            },
        ),
        migrations.AddField(
            model_name='activemanger',
            name='manager_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Manager'),
        ),
    ]
