# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveManger',
            new_name='ActiveManager',
        ),
    ]
